/* LaptopKart Project Documentation — reference data.
   Extracted directly from the deployed metadata / source in force-app/main/default.
   Used by script.js to render the Object, Apex, and LWC reference sections. */

const OBJECTS = [
  {
    name: 'Cart_Activity__c', label: 'Cart Activity', plural: 'Cart Activities', sharing: 'Private',
    namePattern: 'Auto Number — CA-{0000}',
    desc: 'One row per add / remove / clear event on a shopper’s cart, written by <code>cartService.js</code> via <code>LoginCredentialsController.logCartActivity</code>. Purely an activity log — not read back by the storefront, only useful for admin-side visibility into cart behaviour.',
    tag: 'live',
    fields: [
      { api: 'Login_Credentials__c', label: 'Customer Account', type: 'Lookup(Login_Credentials__c)', notes: 'Relationship "Cart_Activities". deleteConstraint = Cascade.', required: true },
      { api: 'Action__c', label: 'Action', type: 'Picklist (restricted)', notes: 'Added / Removed / Cart Cleared', required: true },
      { api: 'Product_Name__c', label: 'Product Name', type: 'Text(255)', notes: '', required: false },
      { api: 'Quantity__c', label: 'Quantity', type: 'Number(18,0)', notes: '', required: false },
      { api: 'Price__c', label: 'Price (per unit)', type: 'Currency(18,2)', notes: '', required: false },
    ],
  },
  {
    name: 'Contact_Us__c', label: 'Contact Us', plural: 'Contact Us Requests', sharing: 'ReadWrite',
    namePattern: 'Auto Number — Query-{00000}',
    desc: 'A support/enquiry ticket submitted from the storefront’s Contact Us page, created by <code>ContactController.submitMessage</code>. Triggers an admin notification email; no automation reacts to status changes.',
    tag: 'live',
    fields: [
      { api: 'Customer__c', label: 'Customer', type: 'Lookup(Contact)', notes: 'Relationship "Contact_Us_Requests". deleteConstraint = SetNull.', required: false },
      { api: 'Email__c', label: 'Email', type: 'Email', notes: '', required: true },
      { api: 'Category__c', label: 'Category', type: 'Picklist (restricted)', notes: 'General Enquiry, Order, Payment, Product, Delivery, Return, Refund, Technical Issue, Other', required: false },
      { api: 'Created_Date__c', label: 'Created Date', type: 'Date', notes: '', required: false },
      { api: 'Low_Medium_High_Urgent__c', label: 'Priority', type: 'Picklist (restricted)', notes: 'Low, Medium, High, Urgent', required: false },
      { api: 'Message__c', label: 'Message', type: 'Rich Text(32768)', notes: '25 visible lines', required: false },
      { api: 'Name__c', label: 'Name', type: 'Text(50)', notes: '', required: true },
      { api: 'Phone__c', label: 'Phone', type: 'Phone', notes: '', required: false },
      { api: 'Status__c', label: 'Status', type: 'Picklist (restricted)', notes: 'New, In Progress, Resolved, Closed', required: false },
      { api: 'Subject__c', label: 'Subject', type: 'Text(100)', notes: '', required: false },
    ],
  },
  {
    name: 'Lead', label: 'Lead (standard — custom fields only)', plural: '', sharing: '(standard)',
    namePattern: '(standard object)',
    desc: 'Standard Salesforce object. LaptopKart uses it as the entry point of checkout — <code>CheckoutController.submitOrder</code> inserts one Lead per order and immediately converts it via <code>Database.convertLead</code>. Only one custom field is added on top of the standard Lead fields.',
    tag: 'live',
    fields: [
      { api: 'Department__c', label: 'Department', type: 'Picklist (restricted)', notes: 'IT, HR, Finance, Sales, Marketing, Operations — used by the generic Welcome-popup lead capture, not the checkout Lead', required: true },
    ],
  },
  {
    name: 'Login_Credentials__c', label: 'Customer Account Detail', plural: 'Customer Account Details', sharing: 'ReadWrite',
    namePattern: 'Auto Number — LC-{0000}',
    desc: 'The record behind LaptopKart’s <strong>custom</strong> storefront login (separate from real Salesforce Experience Cloud users — see the Auth Systems diagram). Password is stored in <strong>plain text by explicit design</strong>, not hashed. Read/written by <code>LoginCredentialsController</code>.',
    tag: 'live',
    fields: [
      { api: 'Password_Text__c', label: 'Password (Plain Text)', type: 'Text(255)', notes: 'Stored unencrypted by design', required: false },
      { api: 'Email__c', label: 'Email', type: 'Email', notes: 'Login username', required: false },
      { api: 'Name__c', label: 'Name', type: 'Text(50)', notes: '', required: false },
      { api: 'Phone__c', label: 'Phone', type: 'Phone', notes: '', required: false },
      { api: 'Cart_Items__c', label: 'Current Cart Items', type: 'Long Text Area(32768)', notes: 'Live mirror of the shopper’s cart, overwritten by cartService.js on every cart change — not meant to be hand-edited', required: false },
    ],
  },
  {
    name: 'Order', label: 'Order (standard — custom fields only)', plural: '', sharing: 'Private',
    namePattern: '(standard object)',
    desc: 'Standard Salesforce object, created automatically by <code>OrderService.createOrders</code> when an Opportunity is Closed Won. Three custom fields extend it for the storefront’s payment tracking and guest-sharing model.',
    tag: 'live',
    fields: [
      { api: 'Payment_Status__c', label: 'Payment Status', type: 'Picklist (restricted)', notes: 'Unpaid, Partially Paid, Fully Paid — recalculated by PaymentService.calculateOrderPayments', required: false },
      { api: 'Total_Paid__c', label: 'Total Paid', type: 'Currency(18,0)', notes: 'Sum of Successful Payment__c rows for this Order', required: false },
      { api: 'Website_Order__c', label: 'Website Order', type: 'Checkbox', notes: 'True when created via the storefront checkout — the criteria field for the Guest User sharing rule that lets Guest read back its own Order', required: false },
    ],
  },
  {
    name: 'Order_Tracking__c', label: 'Order Tracking', plural: 'OrderTrackings', sharing: 'ReadWrite',
    namePattern: 'Text (not Auto Number)',
    desc: 'One row per Order, created by <code>OrderTrackingService</code> the moment an Order moves Draft → Activated, and updated to Cancelled if the order is later cancelled. Drives the 5-step progress tracker shown on Order Confirmation / Order Tracking pages.',
    tag: 'live',
    fields: [
      { api: 'Delivery_Date__c', label: 'Delivery Date', type: 'Date', notes: 'Set to today + 5 days at creation', required: false },
      { api: 'Order__c', label: 'Order', type: 'Lookup(Order)', notes: 'Relationship "OrderTrackings". deleteConstraint = SetNull.', required: false },
      { api: 'Tracking_NUmber__c', label: 'Tracking NUmber', type: 'Text(18)', notes: '⚠ casing typo present in the real API name/label — documented as-is, not a rendering error', required: false },
      { api: 'Delivery_Status__c', label: 'Delivery Status', type: 'Picklist (restricted)', notes: 'Pending, Shipped, Out for Delivery, Delivered, Cancelled', required: false },
    ],
  },
  {
    name: 'Payment__c', label: 'Payment', plural: 'Payments', sharing: 'Private',
    namePattern: 'Text (not Auto Number)',
    desc: 'One row per payment attempt against an Order (Cash on Delivery, or a verified Razorpay transaction). Insert/update fires <code>PaymentTrigger</code>, which validates the amount, recalculates the parent Order’s totals, and — on first transition to Successful — emails the customer.',
    tag: 'live',
    fields: [
      { api: 'Amount__c', label: 'Amount', type: 'Currency(18,0)', notes: 'Must be > 0 — enforced by a validation rule', required: false },
      { api: 'Order__c', label: 'Order', type: 'Lookup(Order)', notes: 'Relationship "Payments1". deleteConstraint = SetNull.', required: false },
      { api: 'Payment_Date__c', label: 'Payment Date', type: 'Date', notes: '', required: false },
      { api: 'Payment_Status__c', label: 'Payment Status', type: 'Picklist (restricted)', notes: 'Pending, Successful, Failed, Refunded', required: false },
      { api: 'Transaction_ID__c', label: 'Transaction ID', type: 'Text(100)', notes: 'Razorpay payment id, UTR number, or a generated placeholder for COD', required: false },
      { api: 'Payment_Method__c', label: 'Payment Method', type: 'Picklist (restricted)', notes: 'Cash, Card, Net Banking, Online', required: false },
    ],
    validationRules: [
      { name: 'Payment_Amount_Must_Be_Greater_Than_Zero', formula: 'OR(ISBLANK(Amount__c), Amount__c <= 0)', message: 'Payment Amount must be greater than 0.' },
    ],
  },
];

const APEX = [
  // --- Core checkout / payment pipeline ---
  { name: 'CheckoutController', group: 'Core Pipeline', sharing: 'without sharing', tag: 'live',
    desc: 'The heart of the storefront: runs the guest-user checkout pipeline end-to-end (Lead → Account/Contact/Opportunity → Order → Order_Tracking__c → Payment__c), verifies Razorpay payments server-side, sends the confirmation email, and reassigns ownership to the admin user.',
    methods: [
      { sig: 'createRazorpayPaymentLink(amount, customerName, customerEmail, customerPhone, callbackUrl) : RazorpayService.PaymentLinkResult', desc: '@AuraEnabled. Thin wrapper that calls RazorpayService.createPaymentLink and turns any failure into a generic AuraHandledException.' },
      { sig: 'submitOrder(inputJson) : OrderResult', desc: '@AuraEnabled. The full 10-step order-creation pipeline — see the dedicated flowchart.' },
      { sig: 'cancelOrder(orderId) : void', desc: '@AuraEnabled. Sets Order.Status = Cancelled, which fires OrderTrigger → OrderTrackingService to mark tracking Cancelled.' },
      { sig: 'getOrdersByEmail(email) : List<OrderSummary>', desc: '@AuraEnabled(cacheable). Looks up every Website_Order__c for a shopper by email.' },
      { sig: 'getOrders(orderIds) : List<OrderSummary>', desc: '@AuraEnabled(cacheable). Looks up specific orders by Id, for locally-remembered order ids.' },
    ],
    calls: ['RazorpayService.fetchPayment', 'RazorpayService.createPaymentLink', 'Database.convertLead (platform)', 'OrderInvoiceController (indirectly, PDF invoice)'],
    calledBy: ['techBasketPayment LWC', 'techBasketMyAccount LWC', 'techBasketOrderHistory (via orderService)'],
  },
  { name: 'RazorpayService', group: 'Core Pipeline', sharing: 'without sharing', tag: 'live',
    desc: 'Thin REST wrapper around Razorpay’s Payment Links API, authenticated via the <code>callout:Razorpay</code> Named Credential (no secret ever touches Apex or the browser).',
    methods: [
      { sig: 'createPaymentLink(amountRupees, customerName, customerEmail, customerPhone, callbackUrl) : PaymentLinkResult', desc: 'POST /payment_links — returns paymentLinkId + shortUrl to redirect the shopper to.' },
      { sig: 'fetchPayment(razorpayPaymentId) : PaymentDetails', desc: 'GET /payments/{id} — the server-side re-verification call; returns status + amountInPaise.' },
    ],
    calls: ['Razorpay REST API (external, via Named Credential)'],
    calledBy: ['CheckoutController.createRazorpayPaymentLink', 'CheckoutController.submitOrder'],
  },
  { name: 'OrderService', group: 'Core Pipeline', sharing: 'without sharing', tag: 'live',
    desc: 'Creates the Order + OrderItem records from a batch of just-Closed-Won Opportunities. Pure automation — no @AuraEnabled surface.',
    methods: [
      { sig: 'createOrders(closedWonOpps) : void', desc: 'Bulk-builds one Draft Order per Opportunity (SYSTEM_MODE), then bulk-inserts OrderItems copied from each Opportunity’s OpportunityLineItems.' },
    ],
    calls: ['SOQL/DML only'],
    calledBy: ['OpportunityTriggerHandler.handleAfterUpdate'],
  },
  { name: 'OrderTrackingService', group: 'Core Pipeline', sharing: 'without sharing', tag: 'live',
    desc: 'Creates or updates Order_Tracking__c in response to Order status transitions.',
    methods: [
      { sig: 'handleStatusChanges(newOrders, oldOrderMap) : void', desc: 'Draft→Activated: inserts a tracking row (Pending, delivery date未定 until submitOrder Step 8 fills it in). Activated→Cancelled: updates the existing row to Cancelled.' },
    ],
    calls: ['SOQL/DML only'],
    calledBy: ['OrderTriggerHandler.handleAfterUpdate'],
  },
  { name: 'PaymentService', group: 'Core Pipeline', sharing: 'without sharing', tag: 'live',
    desc: 'All business logic behind Payment__c: amount validation, Order total recalculation, and the payment-confirmation email (with PDF invoice attached).',
    methods: [
      { sig: 'validateSuccessfulPayments(newPayments, oldPaymentMap) : void', desc: 'Sums existing + incoming Successful payments per Order; addError()s the record if the projected total would exceed Order.TotalAmount.' },
      { sig: 'calculateOrderPayments(newPayments, oldPaymentMap) : void', desc: 'Recomputes Order.Total_Paid__c and Order.Payment_Status__c (Unpaid / Partially Paid / Fully Paid), handling a Payment moved between Orders too.' },
      { sig: 'sendPaymentConfirmationEmails(newPayments, oldPaymentMap) : void', desc: 'For payments that just became Successful: builds an HTML email and attaches a PDF invoice rendered from OrderInvoiceController’s Visualforce page.' },
    ],
    calls: ['OrderInvoiceController (via Page.OrderInvoice.getContentAsPDF)', 'Messaging.sendEmail (platform)'],
    calledBy: ['PaymentTriggerHandler.validatePayments', 'PaymentTriggerHandler.handleAfterInsertOrUpdate'],
  },
  { name: 'OrderInvoiceController', group: 'Core Pipeline', sharing: 'without sharing (WITH SYSTEM_MODE queries)', tag: 'live',
    desc: 'Backs the Visualforce PDF invoice page — used both by the customer-facing "Download Invoice" button and the automatic PDF attached to payment-confirmation emails.',
    methods: [
      { sig: 'getHasOrder / getCustomerName / getShippingAddress / getInvoiceDate / getBalanceDue / getIsCashOnDelivery / getIsOnlinePayment / getPaymentStatusLabel', desc: 'Visualforce getters; constructor reads ?orderId= and loads Order, Contact, OrderItem lines, latest Payment__c, Order_Tracking__c.' },
    ],
    calls: ['SOQL only'],
    calledBy: ['PaymentService.sendPaymentConfirmationEmails (PDF render)', 'Order Confirmation page (window.open to the VF URL)', 'orderPaymentDashboard (admin, direct link)'],
  },
  // --- Trigger handlers ---
  { name: 'OpportunityTriggerHandler', group: 'Trigger Handlers', sharing: 'without sharing', tag: 'live',
    desc: 'Detects Opportunities that just transitioned into Closed Won and hands them to OrderService.',
    methods: [{ sig: 'handleAfterUpdate(newOpps, oldOppMap) : void', desc: 'Filters to StageName now Closed Won / previously not; calls OrderService.createOrders on the filtered set.' }],
    calls: ['OrderService.createOrders'], calledBy: ['OpportunityTrigger (after update)'],
  },
  { name: 'OrderTriggerHandler', group: 'Trigger Handlers', sharing: 'without sharing', tag: 'live',
    desc: 'Thin pass-through handler for OrderTrigger.',
    methods: [{ sig: 'handleAfterUpdate(newOrders, oldOrderMap) : void', desc: 'Passes straight through to OrderTrackingService.handleStatusChanges — no filtering of its own.' }],
    calls: ['OrderTrackingService.handleStatusChanges'], calledBy: ['OrderTrigger (after update)'],
  },
  { name: 'PaymentTriggerHandler', group: 'Trigger Handlers', sharing: 'without sharing', tag: 'live',
    desc: 'Thin dispatcher for PaymentTrigger — the only trigger with both before and after logic.',
    methods: [
      { sig: 'validatePayments(newPayments, oldPaymentMap) : void', desc: 'before insert/update — calls PaymentService.validateSuccessfulPayments (can reject the save).' },
      { sig: 'handleAfterInsertOrUpdate(newPayments, oldPaymentMap) : void', desc: 'after insert/update — calls PaymentService.calculateOrderPayments then sendPaymentConfirmationEmails.' },
    ],
    calls: ['PaymentService.*'], calledBy: ['PaymentTrigger (before + after insert/update)'],
  },
  { name: 'AccountTriggerHandler', group: 'Trigger Handlers', sharing: '(none declared)', tag: 'dead',
    desc: 'Only updatePhone() is live code (writes an audit note when Phone changes) — but accountTrigger’s call to it is commented out, so it never actually runs.',
    methods: [{ sig: 'updatePhone(accList, accOldMap) : void', desc: 'Not called by any active trigger.' }],
    calls: [], calledBy: ['nobody (accountTrigger body is commented out)'],
  },
  { name: 'OpprtunityClosedWonHandler', group: 'Trigger Handlers', sharing: '(none declared)', tag: 'dead',
    desc: 'Broken/dead code: references Account.Customer_Status__c and Account.Total_Won_Amount__c, fields that do not exist anywhere in this org. Its only call site (in OpportunityTrigger) is commented out.',
    methods: [{ sig: 'updateAccountDetails(oppList, oldMap) : void', desc: 'Would fail to compile if actually wired up — left disconnected.' }],
    calls: [], calledBy: ['nobody'],
  },
  // --- Internal / admin ---
  { name: 'OrderPaymentController', group: 'Internal / Admin', sharing: 'with sharing (WITH USER_MODE)', tag: 'live',
    desc: 'Backs the internal orderPaymentDashboard Lightning component embedded on the Order record page — read-only Order/Payment lookups for internal (non-guest) users.',
    methods: [
      { sig: 'getOrderDetails(orderId) : OrderDetails', desc: '@AuraEnabled(cacheable=true).' },
      { sig: 'getPayments(orderId) : List<PaymentDetails>', desc: '@AuraEnabled(cacheable=true).' },
    ],
    calls: ['SOQL only'], calledBy: ['orderPaymentDashboard LWC'],
  },
  { name: 'OrderPaymentReconciliationBatch', group: 'Internal / Admin', sharing: '(none declared)', tag: 'live',
    desc: 'Database.Batchable safety net: re-derives Total_Paid__c / Payment_Status__c on every Activated, not-fully-paid Order from its actual Successful Payment__c rows — in case a real-time trigger update was ever missed. Default batch size (200), no explicit scope set.',
    methods: [
      { sig: 'start(bc) : Database.QueryLocator', desc: 'Order WHERE Status=\'Activated\' AND Payment_Status__c != \'Fully Paid\'' },
      { sig: 'execute(bc, orders) : void', desc: 'Aggregates SUM(Amount__c) from Successful Payment__c grouped by Order; recomputes and bulk-updates Payment_Status__c.' },
      { sig: 'finish(bc) : void', desc: 'No-op.' },
    ],
    calls: ['SOQL/DML only'], calledBy: ['OrderPaymentReconciliationScheduler.execute'],
  },
  { name: 'OrderPaymentReconciliationScheduler', group: 'Internal / Admin', sharing: '(none declared)', tag: 'limitation',
    desc: 'Schedulable trigger for the reconciliation batch. ⚠ No System.schedule(...) call or CronTrigger metadata exists anywhere in this project — it is not currently auto-scheduled. Must be activated manually via Setup ▸ Apex Classes ▸ Schedule Apex, or an anonymous-Apex System.schedule() call.',
    methods: [{ sig: 'execute(sc) : void', desc: 'Database.executeBatch(new OrderPaymentReconciliationBatch())' }],
    calls: ['OrderPaymentReconciliationBatch'], calledBy: ['(not currently scheduled by any deployed metadata)'],
  },
  { name: 'ProductCatalogController', group: 'Internal / Admin', sharing: 'without sharing', tag: 'live',
    desc: 'Public storefront product catalog reader — returns active PricebookEntry/Product2 rows from the Standard Price Book, filtering out Salesforce’s own sample data by a name-prefix deny-list (GenWatt, Installation:, SLA:).',
    methods: [{ sig: 'getProducts() : List<ProductView>', desc: '@AuraEnabled(cacheable=true).' }],
    calls: ['SOQL only'], calledBy: ['productDataService.js (loadProducts)'],
  },
  // --- Login / lead capture ---
  { name: 'LoginCredentialsController', group: 'Login & Lead Capture', sharing: 'without sharing', tag: 'live',
    desc: 'The real, custom LaptopKart login system, built entirely on Login_Credentials__c (plaintext password by design — not real Salesforce authentication). Also mirrors the live cart and logs cart activity.',
    methods: [
      { sig: 'signUp(name, email, phone, password) : AccountSession', desc: '@AuraEnabled.' },
      { sig: 'logIn(email, password) : AccountSession', desc: '@AuraEnabled.' },
      { sig: 'requestPasswordReset(email, phone, message) : void', desc: '@AuraEnabled. Creates a Task for the admin — no real email reset flow.' },
      { sig: 'updateCartSnapshot(loginCredentialsId, cartSummary) : void', desc: '@AuraEnabled.' },
      { sig: 'logCartActivity(loginCredentialsId, action, productName, quantity, price) : void', desc: '@AuraEnabled. Writes a Cart_Activity__c row.' },
    ],
    calls: ['SOQL/DML only'], calledBy: ['authService.js', 'cartService.js', 'techBasketMyAccount LWC'],
  },
  { name: 'ContactController', group: 'Login & Lead Capture', sharing: 'without sharing', tag: 'live',
    desc: 'Backs the storefront Contact Us form — saves a Contact_Us__c ticket and emails the admin.',
    methods: [{ sig: 'submitMessage(name, email, phone, subject, message) : void', desc: '@AuraEnabled.' }],
    calls: ['Database.insert, Messaging.sendEmail (platform)'], calledBy: ['techBasketContactUs LWC'],
  },
  { name: 'WelcomeLeadController', group: 'Login & Lead Capture', sharing: 'without sharing', tag: 'live',
    desc: 'Homepage "welcome popup" lightweight lead capture (top-of-funnel, not a checkout) — creates a plain Lead and emails the admin.',
    methods: [{ sig: 'submitWelcomeLead(name, email, laptopType) : void', desc: '@AuraEnabled.' }],
    calls: ['Database.insert, Messaging.sendEmail (platform)'], calledBy: ['techBasketWelcomePopup LWC'],
  },
  { name: 'RegistrationController', group: 'Login & Lead Capture', sharing: 'without sharing', tag: 'live',
    desc: 'Creates a real Salesforce Experience Cloud login (Customer Community Login User) — the second, independent authentication system. Reuses an existing Contact/Account if the email already has one without a User.',
    methods: [{ sig: 'registerUser(input : RegistrationInput) : void', desc: '@AuraEnabled. Calls Site.createExternalUser(...).' }],
    calls: ['Site.createExternalUser (platform)'], calledBy: ['techBasketSignUp LWC'],
  },
  // --- Boilerplate / unused ---
  { name: 'ChangePasswordController', group: 'Boilerplate / Unused', sharing: 'with sharing', tag: 'dead',
    desc: 'Standard Salesforce Sites/Communities password-change boilerplate. Not part of the custom login system.',
    methods: [{ sig: 'changePassword() : PageReference', desc: 'Site.changePassword(...)' }], calls: ['Site API'], calledBy: ['MyProfilePageController (navigates to its VF page, no direct call)'],
  },
  { name: 'CommunitiesLandingController', group: 'Boilerplate / Unused', sharing: 'with sharing', tag: 'dead',
    desc: 'Standard Experience Cloud landing-page forwarder boilerplate.',
    methods: [{ sig: 'forwardToStartPage() : PageReference', desc: 'Network.communitiesLanding()' }], calls: ['Network API'], calledBy: [],
  },
  { name: 'CommunitiesLoginController', group: 'Boilerplate / Unused', sharing: 'global with sharing', tag: 'dead',
    desc: 'Standard Experience Cloud login-forwarder boilerplate.',
    methods: [{ sig: 'forwardToAuthPage() : PageReference', desc: 'Network.forwardToAuthPage(...)' }], calls: ['Network API'], calledBy: [],
  },
  { name: 'CommunitiesSelfRegConfirmController', group: 'Boilerplate / Unused', sharing: 'with sharing', tag: 'dead',
    desc: 'Backs the "check your email" confirmation VF page shown after self-registration. No logic.',
    methods: [], calls: [], calledBy: [],
  },
  { name: 'CommunitiesSelfRegController', group: 'Boilerplate / Unused', sharing: '(none declared)', tag: 'dead',
    desc: 'Standard Experience Cloud self-registration boilerplate; profileId/accountId placeholders left unfilled — not functional as-is.',
    methods: [{ sig: 'registerUser() : PageReference', desc: 'Site.createExternalUser(...), Site.login(...)' }], calls: ['Site API'], calledBy: [],
  },
  { name: 'MicrobatchSelfRegController', group: 'Boilerplate / Unused', sharing: '(none declared)', tag: 'dead',
    desc: 'Standard async self-registration boilerplate (micro-batch user creation). Placeholders unfilled — not functional.',
    methods: [{ sig: 'registerUser() : PageReference', desc: 'Network.createExternalUserAsync(...)' }], calls: ['Network API'], calledBy: [],
  },
  { name: 'ForgotPasswordController', group: 'Boilerplate / Unused', sharing: 'with sharing', tag: 'dead',
    desc: 'Standard Sites/Communities forgot-password boilerplate — separate from LoginCredentialsController.requestPasswordReset.',
    methods: [{ sig: 'forgotPassword() : PageReference', desc: 'Site.forgotPassword(username)' }], calls: ['Site API'], calledBy: [],
  },
  { name: 'MyProfilePageController', group: 'Boilerplate / Unused', sharing: 'with sharing', tag: 'dead',
    desc: 'Portal user profile edit VF page controller (blocks Guest users). Not part of the LWR storefront.',
    methods: [{ sig: 'getUser / getIsEdit / edit / save / changePassword / cancel', desc: 'Standard VF profile page controller methods.' }], calls: ['Page.ChangePassword (reference only)'], calledBy: [],
  },
  { name: 'SiteLoginController', group: 'Boilerplate / Unused', sharing: 'global with sharing', tag: 'dead',
    desc: 'Standard Sites boilerplate native-login controller. Not the LaptopKart custom login system.',
    methods: [{ sig: 'login() : PageReference', desc: 'Site.login(...)' }], calls: ['Site API'], calledBy: [],
  },
  { name: 'SiteRegisterController', group: 'Boilerplate / Unused', sharing: 'with sharing', tag: 'dead',
    desc: 'Standard Sites boilerplate portal-user registration. PORTAL_ACCOUNT_ID is an unfilled placeholder — not functional.',
    methods: [{ sig: 'registerUser() : PageReference', desc: 'Site.createPortalUser(...), Site.login(...)' }], calls: ['Site API'], calledBy: [],
  },
  { name: 'ContactSharing', group: 'Boilerplate / Unused', sharing: '(none declared)', tag: 'dead',
    desc: 'Manual ContactShare grant utility. Currently unusable — the org’s Contact OWD isn’t Private, so insert throws "Field is not writeable." Not referenced anywhere.',
    methods: [{ sig: 'shareContactWithUser(contactId, userId) : void', desc: '' }], calls: [], calledBy: [],
  },
  { name: 'contactSharingClass', group: 'Boilerplate / Unused', sharing: '(none declared)', tag: 'dead',
    desc: 'Exact duplicate/earlier practice version of ContactSharing. Same unusable state. Not referenced anywhere.',
    methods: [{ sig: 'shareContactWithUser(ContactId, UserId) : void', desc: '' }], calls: [], calledBy: [],
  },
  { name: 'Objs', group: 'Boilerplate / Unused', sharing: '(none declared)', tag: 'dead',
    desc: 'Scratch/practice class not referenced anywhere in the app — a Map demo plus commented-out SOQL/DML snippets.',
    methods: [{ sig: 'operations() : void', desc: '' }], calls: [], calledBy: [],
  },
];

const TRIGGERS = [
  { name: 'accountTrigger', object: 'Account', events: 'after update (declared)', handler: 'AccountTriggerHandler.updatePhone', tag: 'dead', note: 'Entire trigger body is commented out — fires on nothing.' },
  { name: 'contactTrigger', object: 'Contact', events: 'after update (declared)', handler: '(none)', tag: 'dead', note: 'Entire trigger body is commented out — fires on nothing.' },
  { name: 'OpportunityTrigger', object: 'Opportunity', events: 'after update', handler: 'OpportunityTriggerHandler.handleAfterUpdate', tag: 'live', note: 'Live — the start of the order-creation chain.' },
  { name: 'OrderTrigger', object: 'Order', events: 'after update', handler: 'OrderTriggerHandler.handleAfterUpdate', tag: 'live', note: 'Live — creates/updates Order_Tracking__c.' },
  { name: 'PaymentTrigger', object: 'Payment__c', events: 'before insert, before update, after insert, after update', handler: 'PaymentTriggerHandler (validatePayments / handleAfterInsertOrUpdate)', tag: 'live', note: 'Live — the only trigger with both before and after logic.' },
];

const ROUTES = [
  { fn: 'getHomeRef()', page: 'Home', state: '—', notes: 'System home page' },
  { fn: 'getAboutRef()', page: 'About__c', state: '—', notes: 'About Us' },
  { fn: 'getShopRef(searchOrCategory?)', page: 'Product_Catalog__c', state: 'category', notes: 'Product Catalog; historically brand/search text' },
  { fn: 'getShopRefByCategory(categoryName)', page: 'Product_Catalog__c', state: 'cat', notes: 'Separate state key from getShopRef to avoid collisions' },
  { fn: 'getProductRef(productId)', page: 'Product_Detail__c', state: 'productId', notes: 'Product Detail' },
  { fn: 'getCartRef()', page: 'Shopping_Cart__c', state: '—', notes: 'Cart' },
  { fn: 'getCheckoutRef()', page: 'Checkout__c', state: '—', notes: 'Checkout' },
  { fn: 'getPaymentRef(cartPayload?)', page: 'Payment__c', state: 'd', notes: 'Encoded cart+draft handoff (checkoutService.encodeHandoff)' },
  { fn: 'getOrderConfirmationRef(orderId?)', page: 'Order_Confirmation__c', state: 'orderId', notes: 'Order Confirmation' },
  { fn: 'getAccountRef()', page: 'My_Account__c', state: '—', notes: 'My Account (login/signup + dashboard)' },
  { fn: 'getOrderHistoryRef()', page: 'Order_History__c', state: '—', notes: 'Order History' },
  { fn: 'getOrderTrackingRef(orderId?)', page: 'Order_Tracking__c', state: 'orderId', notes: 'Order Tracking' },
  { fn: 'getContactRef()', page: 'Contact_Us__c', state: '—', notes: 'Contact Us' },
  { fn: 'getSignUpRef()', page: 'Sign_Up_c', state: '—', notes: 'Sign Up' },
  { fn: 'getLoginRef()', page: 'comm__loginPage (special)', state: '—', notes: 'Salesforce’s built-in secure login page' },
];

const LWC_PAGES = [
  { name: 'techBasketHome', route: 'Home', tag: 'lwc', desc: 'Homepage — hero slideshow, stats, brand selector, category grid, featured "Top Picks", why-us cards, testimonials, newsletter.',
    children: ['techBasketWelcomePopup', 'techBasketProductCard (×featured)'], apex: [], services: ['navigationService', 'productDataService', 'toastService', 'categoryService', 'formValidators'] },
  { name: 'techBasketAboutUs', route: 'About__c', tag: 'lwc', desc: 'Company story, stats, values, "Meet the Developers" section, Shop Now CTA.',
    children: [], apex: [], services: ['navigationService'] },
  { name: 'techBasketProductCatalog', route: 'Product_Catalog__c', tag: 'lwc', desc: 'Browse / filter / sort / paginate the product catalog; grid and list views.',
    children: ['techBasketProductCard (grid)'], apex: [], services: ['navigationService', 'productDataService', 'cartService', 'toastService'] },
  { name: 'techBasketProductDetail', route: 'Product_Detail__c', tag: 'lwc', desc: 'Apple-style PDP — gallery, info panel, tabs (Description / Reviews / FAQs — reviews & FAQs are mocked), related products.',
    children: ['techBasketQuantitySelector', 'techBasketProductCard (×related)'], apex: [], services: ['productDataService', 'cartService', 'toastService', 'wishlistService', 'brandService', 'navigationService', 'authService'] },
  { name: 'techBasketCart', route: 'Shopping_Cart__c', tag: 'lwc', desc: 'List cart items, totals, clear-cart confirmation.',
    children: ['techBasketCartItem (×items)', 'techBasketOrderSummary', 'techBasketModal'], apex: [], services: ['navigationService', 'cartService', 'toastService'] },
  { name: 'techBasketCartItem', route: '(child of Cart)', tag: 'lwc', desc: 'One row in the cart — image, name, price, quantity, subtotal, remove.',
    children: ['techBasketQuantitySelector'], apex: [], services: ['navigationService', 'brandService'] },
  { name: 'techBasketOrderSummary', route: '(shared: Cart + Checkout)', tag: 'lwc', desc: 'Totals panel (subtotal / shipping / tax / total) with optional "Proceed to Checkout" button.',
    children: [], apex: [], services: ['navigationService', 'cartCalculations'] },
  { name: 'techBasketCheckout', route: 'Checkout__c', tag: 'lwc', desc: 'Multi-step checkout flow (Shipping → Billing (optional) → Shipping Method), then hands off to Payment. Requires login.',
    children: ['techBasketShippingForm', 'techBasketBillingForm', 'techBasketShippingMethod', 'techBasketOrderSummary'], apex: [], services: ['navigationService', 'cartService', 'checkoutService', 'addressService', 'authService'] },
  { name: 'techBasketShippingForm', route: '(child of Checkout)', tag: 'lwc', desc: 'Shipping address form; can prefill from saved addresses.',
    children: [], apex: [], services: ['addressService', 'formValidators'] },
  { name: 'techBasketBillingForm', route: '(child of Checkout, conditional)', tag: 'lwc', desc: 'Billing address form, shown only if "use same address" is unchecked.',
    children: [], apex: [], services: ['formValidators'] },
  { name: 'techBasketShippingMethod', route: '(child of Checkout)', tag: 'lwc', desc: 'Standard / Express / Overnight shipping method picker (client-side only, static price list).',
    children: [], apex: [], services: [] },
  { name: 'techBasketPayment', route: 'Payment__c', tag: 'lwc', desc: 'Standalone payment page — reads the checkout draft handoff, Online (Razorpay redirect) or Cash on Delivery, submits the order.',
    children: ['techBasketPaymentMethod'], apex: ['CheckoutController.submitOrder', 'CheckoutController.createRazorpayPaymentLink'], services: ['navigationService', 'cartService', 'cartCalculations', 'checkoutService', 'orderService'] },
  { name: 'techBasketPaymentMethod', route: '(child of Payment)', tag: 'lwc', desc: 'Online Payment / Cash on Delivery selector.',
    children: [], apex: [], services: [] },
  { name: 'techBasketOrderConfirmation', route: 'Order_Confirmation__c', tag: 'lwc', desc: 'Post-checkout summary — items, payment, shipping, progress tracker, invoice download.',
    children: ['techBasketOrderProgress'], apex: [], services: ['orderService', 'navigationService', 'toastService'] },
  { name: 'techBasketOrderProgress', route: '(shared: Order Confirmation + Tracking)', tag: 'lwc', desc: '5-step horizontal fulfillment tracker (Placed → Payment → Shipped → Out for Delivery → Delivered), purely presentational.',
    children: [], apex: [], services: [] },
  { name: 'techBasketOrderHistory', route: 'Order_History__c', tag: 'lwc', desc: 'List every website order for this shopper (by remembered email), with View/Cancel actions.',
    children: [], apex: [], services: ['orderService', 'navigationService', 'toastService'] },
  { name: 'techBasketOrderTracking', route: 'Order_Tracking__c', tag: 'lwc', desc: 'Shows tracking info for an order — via nav-state orderId or manual order-number lookup.',
    children: ['techBasketOrderProgress'], apex: [], services: ['orderService'] },
  { name: 'techBasketMyAccount', route: 'My_Account__c', tag: 'lwc', desc: 'Custom login/signup (Login_Credentials__c backed) + logged-in sidebar dashboard: Dashboard summary, Profile, Orders, Addresses, Wishlist, Payment Methods info, Settings.',
    children: [], apex: ['LoginCredentialsController.signUp', 'LoginCredentialsController.logIn', 'LoginCredentialsController.requestPasswordReset', 'CheckoutController.getOrdersByEmail'],
    services: ['authService', 'orderService', 'navigationService', 'toastService', 'addressService', 'wishlistService', 'productDataService', 'accountSettingsService', 'cartService', 'brandService', 'formValidators'] },
  { name: 'techBasketSignUp', route: 'Sign_Up_c', tag: 'lwc', desc: 'Real Salesforce Experience Cloud registration — distinct from the custom My-Account login system.',
    children: [], apex: ['RegistrationController.registerUser'], services: ['navigationService', 'formValidators'] },
  { name: 'techBasketContactUs', route: 'Contact_Us__c', tag: 'lwc', desc: 'Contact form, support info, FAQs, live-chat placeholder.',
    children: [], apex: ['ContactController.submitMessage'], services: ['toastService', 'formValidators'] },
  { name: 'techBasketHeader', route: '(global layout)', tag: 'lwc', desc: 'Top navigation bar — logo, Shop dropdown, About/Contact links, search toggle, account, theme toggle, cart badge, mobile drawer.',
    children: ['techBasketSearch'], apex: [], services: ['navigationService', 'cartService', 'categoryService', 'themeService'] },
  { name: 'techBasketFooter', route: '(global layout)', tag: 'lwc', desc: 'Bottom footer — brand info, quick links, customer service links, social icons, copyright.',
    children: [], apex: [], services: ['navigationService'] },
  { name: 'techBasketSearch', route: '(child of Header)', tag: 'lwc', desc: 'Reusable search box with live autocomplete (in-memory filter, no extra Apex per keystroke).',
    children: [], apex: [], services: ['productDataService'] },
  { name: 'techBasketWelcomePopup', route: '(mounted inside Home)', tag: 'lwc', desc: 'One-time lead-capture modal (name/email/laptop-type), localStorage-gated to show once per browser.',
    children: [], apex: ['WelcomeLeadController.submitWelcomeLead'], services: ['categoryService', 'toastService', 'formValidators'] },
  { name: 'techBasketToast', route: '(global, mounted once)', tag: 'lwc', desc: 'Global toast notification renderer; subscribes to toastService so any component can trigger a toast.',
    children: [], apex: [], services: ['toastService'] },
  { name: 'techBasketModal', route: '(generic reusable)', tag: 'lwc', desc: 'Generic confirm/cancel modal, fully controlled by parent via @api props. Used by Cart for "Clear Cart" confirmation.',
    children: [], apex: [], services: [] },
  { name: 'techBasketCategoryCard', route: '(standalone reusable)', tag: 'lwc', desc: 'Clickable category tile. Not directly instantiated by any page read in this audit — Home renders category buttons inline instead. Available for ad-hoc Experience Builder placement.',
    children: [], apex: [], services: [] },
  { name: 'techBasketQuantitySelector', route: '(shared: Cart Item + Product Detail)', tag: 'lwc', desc: 'Shared [−][qty][+] control, clamped between 1 and maxQuantity.',
    children: [], apex: [], services: [] },
  { name: 'techBasketRating', route: '(standalone reusable)', tag: 'lwc', desc: '0–5 star display with optional review count. Not directly wired into any parent read in this audit — available for ad-hoc placement.',
    children: [], apex: [], services: [] },
  { name: 'techBasketProductCard', route: '(shared: Home, Catalog, Product Detail)', tag: 'lwc', desc: 'Product tile — image cycling, wishlist heart, add-to-cart/qty stepper, Buy Now.',
    children: [], apex: [], services: ['navigationService', 'cartService', 'toastService', 'brandService', 'wishlistService', 'authService'] },
  { name: 'orderPaymentDashboard', route: '(internal Lightning — Order record page)', tag: 'lwc', desc: 'Read-only Order + Payment history dashboard embedded on the internal Order record page (Lightning Experience). NOT part of the LWR storefront.',
    children: [], apex: ['OrderPaymentController.getOrderDetails', 'OrderPaymentController.getPayments'], services: [] },
  { name: 'firstComponents', route: '(scratch/demo)', tag: 'dead', desc: 'Trivial placeholder component, not part of the storefront’s functional tree — a learning/demo artifact.',
    children: [], apex: [], services: [] },
];

const LWC_SERVICES = [
  { name: 'navigationService', desc: 'Centralized LWR page-reference factory — single source of truth for every page API name.', fns: ['getHomeRef()', 'getAboutRef()', 'getShopRef(searchOrCategory?)', 'getShopRefByCategory(categoryName)', 'getProductRef(productId)', 'getCartRef()', 'getCheckoutRef()', 'getPaymentRef(cartPayload?)', 'getOrderConfirmationRef(orderId?)', 'getAccountRef()', 'getOrderHistoryRef()', 'getOrderTrackingRef(orderId?)', 'getContactRef()', 'getSignUpRef()', 'getLoginRef()'] },
  { name: 'authService', desc: 'Client-side, localStorage-backed session for the custom Login_Credentials__c login system (not real Salesforce auth).', fns: ['getSession()', 'isLoggedIn()', 'setSession(session)', 'clearSession()', 'subscribe(callback)'] },
  { name: 'cartService', desc: 'localStorage-backed shopping cart; mirrors state to Login_Credentials__c via Apex (best-effort, fire-and-forget).', fns: ['getCart()', 'getCartCount()', 'getItemQuantity(productId)', 'addItem(product, quantity)', 'updateQuantity(productId, quantity)', 'removeItem(productId)', 'clearCart()', 'subscribe(callback)'] },
  { name: 'cartCalculations', desc: 'Pure order-total arithmetic shared by Order Summary and Payment.', fns: ['calculateSubtotal(items)', 'calculateTax(subtotal) — 5% flat, rounded', 'calculateTotals(items, {shippingCost, discountAmount})'] },
  { name: 'checkoutService', desc: 'Bridges the Checkout page and the standalone Payment page via localStorage and URL-state handoff.', fns: ['saveDraft(draft)', 'getDraft()', 'clearDraft()', 'encodeHandoff(cart, draft)', 'decodeHandoff(raw)'] },
  { name: 'orderService', desc: 'Tracks which Order Ids / emails this browser has placed orders under; bridges to CheckoutController.', fns: ['rememberOrder(orderId)', 'rememberEmail(email)', 'getMyOrders()', 'cancelOrder(orderId)', 'getOrder(orderId)'] },
  { name: 'addressService', desc: 'localStorage-backed saved address book, shared between Checkout and My Account.', fns: ['getAddresses()', 'saveAddress(address)', 'deleteAddress(id)'] },
  { name: 'wishlistService', desc: 'localStorage-backed wishlist (array of product ids).', fns: ['getWishlist()', 'isWishlisted(productId)', 'toggleWishlist(productId)'] },
  { name: 'accountSettingsService', desc: 'localStorage-backed notification preferences for My Account › Account Settings.', fns: ['getSettings()', 'saveSettings(settings)'] },
  { name: 'productDataService', desc: 'Loads and caches the real Apex-backed product catalog once per page session.', fns: ['loadProducts()', 'findById(products, productId)', 'filterByCategory(products, category)', 'filterBySearch(products, term)', 'extractCategories(products)'] },
  { name: 'mockProductData', desc: 'Standalone frontend-only mock catalog (12 hardcoded non-laptop products) — legacy/demo data, separate from the real Apex-backed catalog.', fns: ['PRODUCTS', 'getAllProducts()', 'getProductById(productId)', 'getProductsByCategory(category)', 'searchProducts(term)', 'getCategories()'] },
  { name: 'brandService', desc: 'Source of truth for the 7 laptop brand definitions and deterministic product-photo resolution from brand-scoped static resources.', fns: ['getBrands()', 'getBrandForProduct(productName)', 'getProductImages(productName)'] },
  { name: 'categoryService', desc: 'Infers a real shopping category (Gaming, Business, Ultrabook & Slim, 2-in-1 & Convertible, Chromebook, Everyday) from a product name, since Apex always returns "Laptops".', fns: ['getCategories()', 'getCategoryForProduct(productName)'] },
  { name: 'themeService', desc: 'Site-wide light/dark theme engine — writes --lk-* CSS custom properties onto <html>.', fns: ['getTheme()', 'setTheme(theme)', 'toggleTheme()', 'subscribe(callback)'] },
  { name: 'toastService', desc: 'Pub/sub bridge letting any component trigger a toast without a DOM reference to techBasketToast.', fns: ['showToast(message, variant)', 'subscribe(callback)'] },
  { name: 'formValidators', desc: 'Shared field-format rules/regex/sanitizers used by every form on the site.', fns: ['PHONE_PATTERN / EMAIL_PATTERN / NAME_PATTERN / POSTAL_PATTERN (+ *_ERROR constants)', 'isValidPhone / isValidEmail / isValidName / isValidPostalCode', 'sanitizePhoneInput(value)', 'sanitizePostalInput(value)'] },
];

const ISSUES = [
  { severity: 'design', title: 'Plaintext password storage on Login_Credentials__c', body: 'The custom storefront login stores Password_Text__c unencrypted. This is an explicit, deliberate project decision, not an oversight — documented here for anyone auditing the object later.' },
  { severity: 'design', title: 'Two independent authentication systems', body: 'The custom Login_Credentials__c system (My Account, cart gating) and the real Salesforce Experience Cloud login (Sign Up → RegistrationController → Site.createExternalUser) are completely separate — a shopper can have an account in one without the other. See the Auth Systems diagram.' },
  { severity: 'limitation', title: 'Shipping cost is never actually charged online', body: 'CheckoutController.submitOrder only ever verifies the Razorpay payment against Order.TotalAmount, which reflects the product subtotal only (shipping/tax have no OrderItem representation in this schema). techBasketPayment.js charges totals.subtotal for exactly this reason — shipping has never been collected via any payment method, online or COD, independent of the gateway work.' },
  { severity: 'limitation', title: 'Razorpay test-mode hard limit: 30 Payment Links', body: 'Razorpay’s test-mode account caps Payment Link creation at exactly 30 (confirmed via a direct 429 RATE_LIMIT_EXCEEDED response, description "test mode limit of 30 reached for payment_link"). Purely external to this codebase — not a bug. Once the account moves to live keys this cap does not apply.' },
  { severity: 'limitation', title: 'Razorpay UPI does not reliably redirect back in test mode', body: 'Documented Razorpay Payment Links behaviour: UPI payments don’t redirect to callback_url on Android, and don’t work reliably in Test Mode at all — full end-to-end auto-redirect UPI testing isn’t achievable in test mode regardless of this app’s code.' },
  { severity: 'resolved', title: 'Embedded Razorpay Checkout.js blocked by Lightning Web Security', body: 'The original embedded-popup approach failed because LWS blocks dynamic <script> injection into the page, and this org has no CSP Trusted Site "script-src" option at all (confirmed absent from both metadata and the Setup UI). Resolved by switching to a full-page redirect to Razorpay’s hosted Payment Link page — no third-party script ever loads inside the Salesforce page.' },
  { severity: 'resolved', title: 'Apex "uncommitted work pending" callout error', body: 'Apex disallows an HTTP callout after DML has run in the same transaction. The Razorpay verification callout was moved to the very start of submitOrder, before any of the pipeline’s DML steps run.' },
  { severity: 'bug', title: 'Typo in a live field: Tracking_NUmber__c', body: 'Order_Tracking__c’s tracking-number field has a casing typo baked into both its API name and label (capital U in "NUmber"). Documented as-is since renaming a live field API name would break every reference to it across Apex and LWC.' },
  { severity: 'design', title: 'Dead trigger bodies: accountTrigger and contactTrigger', body: 'Both triggers exist as deployed metadata but their entire bodies are commented out — they compile and are active on their objects, but execute no logic on any event.' },
  { severity: 'design', title: 'Disconnected/placeholder boilerplate controllers', body: 'Roughly a third of the Apex classes in this org (CommunitiesSelfRegController, SiteRegisterController, MicrobatchSelfRegController, ContactSharing, contactSharingClass, Objs, OpprtunityClosedWonHandler, AccountTriggerHandler, and others) are either standard Salesforce Sites/Experience Cloud boilerplate never wired up, or scratch/practice code with unfilled placeholders. None are called from the live automation chain. See the Apex Reference for the full "Boilerplate / Unused" group.' },
  { severity: 'limitation', title: 'Reconciliation batch is not auto-scheduled', body: 'OrderPaymentReconciliationScheduler exists and correctly calls the batch, but no System.schedule(...) call or CronTrigger metadata is deployed anywhere — the nightly safety-net reconciliation does not currently run on its own and must be scheduled manually in Setup.' },
];
